[project]
name = "min-menu-maker"
version = "1.0.0"
description = "Minimal menu maker for python"

[build-system]
requires = ['setuptools>=65']
build-backend = 'setuptools.build_meta'

[tool.setuptools]
py-modules=[]
